name = "FourierNeuralOperators"
uuid = "fad0b1a5-a77e-47d0-848c-9f04c700d34f"
authors = ["AzamatB"]
version = "0.1.0"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"

[compat]
AbstractFFTs = "1.5.0"
Enzyme = "0.13.109"
Optimisers = "0.4.7"
Printf = "1.11.0"
Reactant = "0.2.185"
Static = "1.3.1"

[extras]
ReTest = "e0db7c4e-2690-44b9-bad6-7687da720f89"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ReTest"]
